AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample CloudFormation template for cost estimation testing'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # EC2 Instance
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-web-server
        - Key: Environment
          Value: !Ref Environment

  # RDS Instance
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydb
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # S3 Bucket
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Environment}-data-bucket
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Lambda Function
  ProcessFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 300
      MemorySize: 128
      Code:
        ZipFile: |
          def handler(event, context):
              return {
                  'statusCode': 200,
                  'body': 'Hello from Lambda!'
              }

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Parameters:
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database admin password
    MinLength: 8
    AllowedPattern: ^[a-zA-Z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters

Outputs:
  WebServerPublicDNS:
    Description: Public DNSName of the web server
    Value: !GetAtt WebServer.PublicDnsName

  DatabaseEndpoint:
    Description: Database endpoint
    Value: !GetAtt Database.Endpoint.Address

  DataBucketName:
    Description: Name of the data bucket
    Value: !Ref DataBucket

  ProcessFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ProcessFunction.Arn 